In [2]:
import torch
import torch.nn as nn

In [1]:
from pycocotools.coco import COCO as co

In [2]:
dataDir = '/home/jetson/val2017/'
ann = '{}/annotations/stuff_train2017.json'.format(dataDir)

In [3]:
coco = co(ann)

loading annotations into memory...
Done (t=45.49s)
creating index...
index created!


In [6]:
coco.loadRes(ann)

Loading and preparing results...


AssertionError: results in not an array of objects

In [4]:
coco.getAnnIds()

[10000000,
 10000001,
 10000002,
 10000003,
 10000004,
 10000005,
 10000006,
 10000007,
 10000008,
 10000009,
 10000010,
 10000011,
 10000012,
 10000013,
 10000014,
 10000015,
 10000016,
 10000017,
 10000018,
 10000019,
 10000020,
 10000021,
 10000022,
 10000023,
 10000024,
 10000025,
 10000026,
 10000027,
 10000028,
 10000029,
 10000030,
 10000031,
 10000032,
 10000033,
 10000034,
 10000035,
 10000036,
 10000037,
 10000038,
 10000039,
 10000040,
 10000041,
 10000042,
 10000043,
 10000044,
 10000045,
 10000046,
 10000047,
 10000048,
 10000049,
 10000050,
 10000051,
 10000052,
 10000053,
 10000054,
 10000055,
 10000056,
 10000057,
 10000058,
 10000059,
 10000060,
 10000061,
 10000062,
 10000063,
 10000064,
 10000065,
 10000066,
 10000067,
 10000068,
 10000069,
 10000070,
 10000071,
 10000072,
 10000073,
 10000074,
 10000075,
 10000076,
 10000077,
 10000078,
 10000079,
 10000080,
 10000081,
 10000082,
 10000083,
 10000084,
 10000085,
 10000086,
 10000087,
 10000088,
 10000089,
 10000090,

In [26]:
coco.getImgIds()

[391895,
 522418,
 184613,
 318219,
 554625,
 574769,
 60623,
 309022,
 5802,
 222564,
 118113,
 193271,
 224736,
 483108,
 403013,
 374628,
 328757,
 384213,
 293802,
 86408,
 372938,
 386164,
 223648,
 204805,
 113588,
 384553,
 337264,
 368402,
 12448,
 79841,
 515289,
 562150,
 542145,
 412151,
 579003,
 540186,
 242611,
 51191,
 269105,
 294832,
 462565,
 144941,
 173350,
 60760,
 324266,
 166532,
 262284,
 360772,
 191381,
 111076,
 340559,
 258985,
 509822,
 321107,
 229643,
 125059,
 455483,
 436141,
 129001,
 232262,
 61181,
 166323,
 580041,
 326781,
 387362,
 138079,
 556616,
 472621,
 192440,
 86320,
 256668,
 383445,
 565797,
 81922,
 50125,
 364521,
 394892,
 1146,
 310391,
 97434,
 463836,
 241876,
 156832,
 270721,
 462341,
 310103,
 32992,
 122851,
 540763,
 138246,
 197254,
 32907,
 251252,
 37675,
 159537,
 268556,
 271177,
 75051,
 549399,
 85160,
 559665,
 19358,
 459912,
 15827,
 394240,
 510755,
 175831,
 79472,
 250108,
 315601,
 437218,
 503707,
 74331,
 579664

In [8]:
coco.loadAnns(10391895)

[{'area': 663.0,
  'bbox': [178.0, 107.0, 49.0, 33.0],
  'category_id': 168,
  'id': 10391895,
  'image_id': 301047,
  'iscrowd': 0,
  'segmentation': {'counts': ']YQ21e;1000001N10001N10001N2O1O010O1O001O1O10O01O1O001O10O01O1O1O1O2O0O101N1O2N10O0O1O2O0O1]ORE:R;EoD8S;HoD3T;L=O00ckS3',
   'size': [375, 500]}}]

In [14]:
coco.loadCats(100)

[{'id': 100, 'name': 'cardboard', 'supercategory': 'raw-material'}]

In [20]:
len(coco.getAnnIds())

747458

In [27]:
coco.loadImgs(391895)

[{'coco_url': 'http://images.cocodataset.org/train2017/000000391895.jpg',
  'date_captured': '2013-11-14 11:18:45',
  'file_name': '000000391895.jpg',
  'flickr_url': 'http://farm9.staticflickr.com/8186/8119368305_4e622c8349_z.jpg',
  'height': 360,
  'id': 391895,
  'license': 3,
  'width': 640}]

In [3]:
pool = nn.MaxPool2d(2, stride=2, padding=1)

In [4]:
conv = nn.Conv2d(3, 8, kernel_size=3, stride=1, padding=1)

In [5]:
t = torch.Tensor([x for x in range(48)])

In [6]:
t = t.reshape([1, 3, 4, 4])

In [7]:
t

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[16., 17., 18., 19.],
          [20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.]],

         [[32., 33., 34., 35.],
          [36., 37., 38., 39.],
          [40., 41., 42., 43.],
          [44., 45., 46., 47.]]]])

In [8]:
pool(t)

tensor([[[[ 0.,  2.,  3.],
          [ 8., 10., 11.],
          [12., 14., 15.]],

         [[16., 18., 19.],
          [24., 26., 27.],
          [28., 30., 31.]],

         [[32., 34., 35.],
          [40., 42., 43.],
          [44., 46., 47.]]]])

In [10]:
cnv = conv(t)

In [11]:
print(cnv.shape)
cnv

torch.Size([1, 8, 4, 4])


tensor([[[[ 15.5885,  10.6009,  10.6686,  -0.4233],
          [ 22.5415,  19.1338,  19.3776,   5.0904],
          [ 24.1475,  20.1090,  20.3528,   4.3468],
          [  6.7318,   6.1305,   6.0237,  -1.2019]],

         [[  4.8117,   8.1860,   8.5177,  13.8324],
          [  1.9871,   7.7028,   8.0167,  20.4284],
          [  2.9533,   8.9585,   9.2725,  23.4468],
          [  5.1184,   0.3292,   0.3527,   8.3207]],

         [[-20.4095, -13.9455, -14.3704,  -7.6926],
          [-20.2176, -13.8540, -14.0870,  -7.1405],
          [-20.9815, -14.7861, -15.0192,  -8.3503],
          [ -5.5033,   1.5587,   1.6849,   5.4451]],

         [[-15.2746, -17.8397, -18.7108,  -8.4214],
          [-16.7161, -21.5170, -22.3224,  -6.4113],
          [-19.6423, -24.7386, -25.5440,  -7.1793],
          [ -3.0731,  -2.2919,  -2.4430,   7.4419]],

         [[  5.7337,  11.6061,  12.1015,   0.6686],
          [  9.9431,  21.0064,  21.8640,   1.4513],
          [ 11.0858,  24.4368,  25.2944,   2.2980],
    